spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myneighbors
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
server:
  port: 80
